export const cuisineList = [
  "Biryani",
  "Butter Chicken",
  "Paneer Tikka",
  "Vada Pav",
  "Pav Bhaji",
  "Misal Pav",
  "Puran Poli",
  "Modak",
  "Shrikhand",
  "Sabudana Khichdi",
  "Thali",
  "Aamti",
  "Poha",
  "Upma",
  "Bhakri",
  "Pithla",
  "Kolhapuri Chicken",
  "Sol Kadhi",
  "Bombil Fry",
  "Kombdi Vade",
  "Malvani Fish Curry",
  "Ukadiche Modak",
  "Bharli Vangi",
  "Kande Pohe",
  "Maharashtrian Snacks",
  "Maharashtrian Sweets",
];
